# Generated by Django 5.0.6 on 2024-07-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_profile_address_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
