# Generated by Django 5.0.6 on 2024-07-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('name_kor', models.CharField(max_length=30)),
                ('name_eng', models.CharField(max_length=30)),
                ('model_no', models.CharField(max_length=20)),
                ('release_date', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('img_url', models.CharField(max_length=200)),
                ('product_detail_url', models.CharField(max_length=200)),
            ],
        ),
    ]
