# Generated by Django 5.0.6 on 2024-07-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kor', models.CharField(max_length=30)),
                ('trade_date', models.CharField(max_length=30)),
                ('trade_size', models.CharField(max_length=30)),
                ('trade_price', models.IntegerField()),
            ],
        ),
    ]
