# Generated by Django 5.0.6 on 2024-07-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
