# Generated by Django 5.0.6 on 2024-07-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0004_remove_trade_trade_date_remove_trade_trade_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='proudct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kream.product'),
        ),
    ]
