# Generated by Django 5.0.6 on 2024-07-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0005_trade_proudct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='proudct',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='name_kor',
        ),
    ]
