# Generated by Django 5.0.6 on 2024-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0006_rename_proudct_trade_product_remove_trade_name_kor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kor', models.CharField(max_length=30)),
                ('trade_size', models.CharField(max_length=10)),
                ('trade_price', models.IntegerField(default=0)),
                ('trade_year', models.IntegerField(default=0)),
                ('trade_month', models.IntegerField(default=0)),
                ('trade_hour', models.IntegerField(default=0)),
            ],
        ),
    ]
