# Generated by Django 5.0.6 on 2024-07-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0007_trade_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade_total',
            name='name_kor',
        ),
        migrations.AddField(
            model_name='trade_total',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kream.product'),
        ),
    ]
