# Generated by Django 5.0.6 on 2024-07-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0008_remove_trade_total_name_kor_trade_total_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
