# Generated by Django 5.0.6 on 2024-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0010_check_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_list',
            name='title',
            field=models.CharField(default='default_title', max_length=100),
        ),
        migrations.AlterField(
            model_name='check_list',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
