# Generated by Django 5.0.6 on 2024-07-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0011_check_list_title_alter_check_list_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_list',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
