# Generated by Django 5.0.6 on 2024-07-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0012_check_list_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check_list',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='check_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
