# Generated by Django 5.0.6 on 2024-07-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kream', '0013_alter_check_list_options_check_list_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_list',
            name='image',
        ),
    ]
